- name: Install Telnet and Python packages
  hosts: web_servers
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  remote_user: ec2-user  # Specify the SSH user here
  roles:
    - role: ../roles/telnet
