name: Trigger Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Set permissions for SSH private key
      run: chmod 600 chabi.pem

    - name: Run Ansible Playbook
      run: ansible-playbook -i inventories/production/hosts playbooks/packages.yml
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
